# Generated by Django 2.0.2 on 2018-04-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='create_date',
            new_name='pub_date',
        ),
    ]
